[project]
name = "pytorch-tinybert"
version = "0.0.0"
description = "Tiny BERT from-scratch (development editable install)"
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
