project:
  name: pytorch-tinybert
  seed: 42

model:
  vocab_size: 30522
  hidden_size: 256
  num_hidden_layers: 3
  num_attention_heads: 4
  intermediate_size: 1024
  max_position_embeddings: 128
  dropout: 0.1

training:
  batch_size: 32
  lr: 5e-5
  weight_decay: 0.01
  epochs: 3
  warmup_steps: 100
